# Source: lighthouse/templates/foghorn-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-foghorn
  labels:
    chart: "lighthouse-0.0.939"
    app: lighthouse-foghorn
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lighthouse-foghorn
  template:
    metadata:
      labels:
        app: lighthouse-foghorn
      annotations:
        jenkins-x.io/hash: 'bc337e4ec708f484f54f2894622d14f3ecb50dc49e8e4938ae5809cef2f123b0'
    spec:
      serviceAccountName: lighthouse-foghorn
      containers:
        - name: lighthouse-foghorn
          image: gcr.io/jenkinsxio/lighthouse-foghorn:0.0.0-PR-1254-5-SNAPSHOT
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=jx"
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: jgoldring
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "HMAC_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: "lighthouse-hmac-token"
                  key: hmac
                  optional: false
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: DEFAULT_PIPELINE_RUN_SERVICE_ACCOUNT
              value: "tekton-bot"
            - name: DEFAULT_PIPELINE_RUN_TIMEOUT
              value: "2h0m0s"
            - name: FILE_BROWSER
              value: "git"
            - name: JX_DEFAULT_IMAGE
              value: "gcr.io/jenkinsxio/builder-maven:2.1.142-761"
            - name: LIGHTHOUSE_DASHBOARD_TEMPLATE
              value: "namespaces/{{ .Namespace }}/pipelineruns/{{ .PipelineRun }}"
            - name: LIGHTHOUSE_VERSIONSTREAM_JENKINS_X_JX3_PIPELINE_CATALOG
              value: "d8ca0ed0352e5beff7a17cdc6b92a94b9b5b15e9"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 128Mi
      terminationGracePeriodSeconds: 180
